In [82]:

import spacy
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np
import pandas as pd

In [2]:
nlp = spacy.load("en_core_web_sm")

In [2]:
def clean_text_and_info(text):
    doc = nlp(text)
    tokens = [token.lemma_.lower() for token in doc if not token.is_stop and not token.is_punct]
    entities = [f"{ent.text}: {ent.label_}" for ent in doc.ents]
    pos_tags = [(token.text, token.pos_) for token in doc]
    print("\nCleaned Tokens:")
    print(tokens)
    print("\nNamed Entities")
    if entities:
        for item in entities:
            print(item)
    else:
        print("No named entity found")
    print("\nPart of speech Tags")
    for word, pos in pos_tags:
        print(f"{word}-- {pos}")
    return tokens, entities, pos_tags

In [17]:
train_dataset = pd.read_csv("train.tsv",sep='\t', header=None)
train_dataset.to_csv("cleaned_train.csv", index=False)

In [66]:
val_dataset = pd.read_csv("valid.tsv",sep='\t', header=None)
val_dataset.to_csv("cleaned_validation.csv", index=False)

In [18]:
train_dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,2635.json,false,Says the Annies List political group supports ...,abortion,dwayne-bohac,State representative,Texas,republican,0.0,1.0,0.0,0.0,0.0,a mailer
1,10540.json,half-true,When did the decline of coal start? It started...,"energy,history,job-accomplishments",scott-surovell,State delegate,Virginia,democrat,0.0,0.0,1.0,1.0,0.0,a floor speech.
2,324.json,mostly-true,"Hillary Clinton agrees with John McCain ""by vo...",foreign-policy,barack-obama,President,Illinois,democrat,70.0,71.0,160.0,163.0,9.0,Denver
3,1123.json,false,Health care reform legislation is likely to ma...,health-care,blog-posting,NaN,NaN,none,7.0,19.0,3.0,5.0,44.0,a news release
4,9028.json,half-true,The economic turnaround started at the end of ...,"economy,jobs",charlie-crist,NaN,Florida,democrat,15.0,9.0,20.0,19.0,2.0,an interview on CNN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10235,5473.json,mostly-true,There are a larger number of shark attacks in ...,"animals,elections",aclu-florida,NaN,Florida,none,0.0,1.0,1.0,1.0,0.0,"interview on ""The Colbert Report"""
10236,3408.json,mostly-true,Democrats have now become the party of the [At...,elections,alan-powell,NaN,Georgia,republican,0.0,0.0,0.0,1.0,0.0,an interview
10237,3959.json,half-true,Says an alternative to Social Security that op...,"retirement,social-security",herman-cain,NaN,Georgia,republican,4.0,11.0,5.0,3.0,3.0,a Republican presidential debate
10238,2253.json,false,On lifting the U.S. Cuban embargo and allowing...,"florida,foreign-policy",jeff-greene,NaN,Florida,democrat,3.0,1.0,3.0,0.0,0.0,a televised debate on Miami's WPLG-10 against ...
10239,1155.json,pants-fire,The Department of Veterans Affairs has a manua...,"health-care,veterans",michael-steele,chairman of the Republican National Committee,Maryland,republican,0.0,1.0,1.0,0.0,2.0,a Fox News interview

In [67]:
train_dataset.columns = [
    "id", "label", "statement", "subject", "speaker", "speaker_job", 
    "state_info", "party_affiliation", "barely_true_counts", "false_counts", 
    "half_true_counts", "mostly_true_counts", "pants_on_fire_counts", "context"
]
val_dataset.columns = [  "id", "label", "statement", "subject", "speaker", "speaker_job", 
    "state_info", "party_affiliation", "barely_true_counts", "false_counts", 
    "half_true_counts", "mostly_true_counts", "pants_on_fire_counts", "context"

]

In [68]:
nlpTrain_df = train_dataset[["label", "statement"]]
nlpVal_df = val_dataset[["label", "statement"]]

In [48]:
nlpTrain_df["label"].unique()

array(['false', 'half-true', 'mostly-true', 'true', 'barely-true',
       'pants-fire'], dtype=object)

In [49]:
nlp_multiclass_labels = {'false':0,
                         'pants-fire':0,
                         'barely-true':0,
                          'half-true':1,
                          'mostly-true':1,
                          'true': 1
                         }

In [69]:
nlpTrain_df_copy = nlpTrain_df.copy() 
nlpVal_df_copy = nlpVal_df.copy()

In [70]:
nlpTrain_df_copy["label"] = nlpTrain_df["label"].map(nlp_multiclass_labels)
nlpVal_df_copy["label"] = nlpVal_df_copy["label"].map(nlp_multiclass_labels)

In [52]:
nlpTrain_df_copy

       label                                          statement
0          0  Says the Annies List political group supports ...
1          1  When did the decline of coal start? It started...
2          1  Hillary Clinton agrees with John McCain "by vo...
3          0  Health care reform legislation is likely to ma...
4          1  The economic turnaround started at the end of ...
...      ...                                                ...
10235      1  There are a larger number of shark attacks in ...
10236      1  Democrats have now become the party of the [At...
10237      1  Says an alternative to Social Security that op...
10238      0  On lifting the U.S. Cuban embargo and allowing...
10239      0  The Department of Veterans Affairs has a manua...

[10240 rows x 2 columns]

In [85]:
tfIDF_vectorizer = TfidfVectorizer(lowercase=True,stop_words='english',max_df=0.95, min_df=1,  ngram_range=(1,2))

In [86]:
X_tfDIF_train = tfIDF_vectorizer.fit_transform(nlpTrain_df_copy["statement"])
X_tfDIF_val = tfIDF_vectorizer.transform(nlpVal_df_copy["statement"])

In [87]:
Y_tfDIF_train = nlpTrain_df_copy["label"].values
Y_tfDIF_val = nlpVal_df_copy["label"].values

In [88]:
logistic_regresion_model = LogisticRegression(max_iter=1000)

In [89]:
logistic_regresion_model.fit(X_tfDIF_train,Y_tfDIF_train)

LogisticRegression(max_iter=1000)

In [90]:
y_val_prediction = logistic_regresion_model.predict(X_tfDIF_val)

In [91]:
print(classification_report(Y_tfDIF_val,y_val_prediction))

              precision    recall  f1-score   support

           0       0.65      0.44      0.52       616
           1       0.60      0.78      0.68       668

    accuracy                           0.62      1284
   macro avg       0.62      0.61      0.60      1284
weighted avg       0.62      0.62      0.60      1284